### ISSUE TITLE
 Call to undefined assert_instance()

### ISSUE THREAD

**Issue by salawatbro** [CristianHG2/laravel-data-scramble#1]
<img width="1241" alt="image" src="https://github.com/CristianHG2/laravel-data-scramble/assets/70514229/6bc0babc-5c67-4275-a71a-b54eb3938ade">

I can't find the assert_instance function

**Comment by CristianHG2** [comment]
Hello, sorry, this code I grabbed from one of my projects features an internal utility library.

This is primarily for type safety if you use something like PHPStan. You should be able to remove it, and it should work the same:

```
return $dataObject->getValidationRules([]);
```

I've updated the repo with this change. Thank you for reporting!
